language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:local || travis_terminate 1;
  fi
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - secure: L2WHX4RIJZB0HoRv8icbLgHwaDrEskv9TCoAqWu9OwzOFu3Bj+cveiIITJX7cHO79mnN8dnotuYIMx0pKnlQ4azGHLwzlXUuxc8o02zJtnXHWrdA8Y0UWb1elghorIf/FwLhp5O3iMI8HNO6HotfDo8aM6inRpu9yiQpDk0Nq49XwfrH7vqFDG4ZAopJpM/4RwZNBqM/1wgBA4BWMgQfG0WL96BZ6gVAQQyBE9Ptt7vvHJ7V13ynYp99BMXY224Ki4pdvfYkbZjUvmq2b6rYm+JnwIk6LDYsqPWPXIkg2UtiUS7aBz6/cB9wZ1j54OVK1nAcN2e2E8V4bvCgS1aItV1vE2G80Nb2i5YjewdHbhirH0JRv+WlgZuvSpjwIS4+7j5sYLiIkx52UC/mHZmARhLVemhBPlidKN2hfI5ZuLkr8P4gpKcLBcwRpZg3nbyKgT5vh8x7PP1IcjtlRtRT/KHQjMHXE+luA4uurBo1jp4kf4JrSGFF5OKfwJvj3FU6HVWPsM41SOvCVLgQyvp1fCbWatHla1tpk1tMZvq16hqTR1HPfNn9QZyFfvV0geso094rCH7536Muv2xdZlzZCioPi8SAHZENhpfXo0eTQLHoyodIh+b+/C/GdysetpbDY85z7EdJuh4DF3VLRJZEzQYyBA03oOvSLm3IcjO99C4=
